# Documentation:
# https://trovu.net/docs/users/advanced/#custom-configuration
namespaces:
- o
- de
- github: .
  name: my
- name: mydomain
  url: C:/shortcuts.yml
# defaultKeyword: g 
language: de
country: de
